# Generated by Django 2.2.14 on 2020-07-16 10:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MFS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('village', models.CharField(choices=[('Bhootgarh', 'Bhootgarh'), ('Majra', 'Majra')], max_length=2)),
                ('name_of_surveyor', models.CharField(max_length=500)),
                ('house_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('household_number', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
