# Generated by Django 2.2.14 on 2020-07-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MFS', '0002_auto_20200716_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfs',
            name='village',
            field=models.CharField(choices=[('Bhootgarh', 'Bhootgarh'), ('Majra', 'Majra')], max_length=100),
        ),
    ]
